on:
  release:
    types: [created]

name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
      	uses: actions/checkout@master
      - 
        name: Set up Go
      	uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      -
        name: Build
        run: go build -o bin/ -v ./...
      -
        name: Test
        run: go test -v ./...
      - 
        name: Upload the artifacts
      	uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bin/*'
